# NumPy
- Short for Numerical Python
- Foundational Package for Numerical computing in python
- Provides an ndarray object which is an efficient multidimensional array providing fast array oriented operations
- Provides a lot of functions

In [2]:
import numpy as np

# Creating ndarrays

##### Creating ndarray from an object

In [2]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [3]:
type(a1)

numpy.ndarray

In [4]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [5]:
a1 = np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a1.shape

(10,)

In [7]:
a1.dtype

dtype('int32')

In [8]:
a1.ndim

1

In [9]:
a1 = np.array([[1,2,3], [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a1.shape

(2, 3)

In [12]:
a1.ndim

2

In [13]:
a1 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a1.shape

(2, 2, 2)

In [15]:
a1.ndim

3

In [16]:
a = np.array([1,2,3,4,5], dtype = np.float)
a

array([1., 2., 3., 4., 5.])

In [17]:
a.dtype

dtype('float64')

In [18]:
a = np.array([1.5,2.6,3.1,4.8,5.2], dtype = np.int)
a

array([1, 2, 3, 4, 5])

In [19]:
a.dtype

dtype('int32')

### Typecasting ndarrays

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a = a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [5]:
a = a.astype(str)
a

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

In [22]:
a = a.astype(int)
a

array([1, 2, 3, 4, 5])

### Creating ndarrays by specifying a range

In [23]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a1 = np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a1 = np.arange(10, dtype = np.float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Creating ndarrays of ones

In [30]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
np.ones((5,5), dtype = np.int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating ndarray of zeros

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating ndarray of a specific value

In [37]:
np.full((4,5), fill_value = 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

### Creating an identity matrix

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# --------------------------------------------------------------------------------------
# Operations on ndarrays

In [8]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [9]:
# list]
l1 = [1,2,3,4,5,6]
l2= [1,2,3,4,5,6]
l1 + l2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [10]:
a1 + 2

array([3, 4, 5, 6, 7, 8])

In [11]:
a2 = np.array([4,5,6,7,8,9])
a2

array([4, 5, 6, 7, 8, 9])

In [12]:
a1 + a2

array([ 5,  7,  9, 11, 13, 15])

In [13]:
a1 + [2,3,4,5,6,7]

array([ 3,  5,  7,  9, 11, 13])

In [14]:
a1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [15]:
a1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [45]:
a1 * a2

array([ 4, 10, 18, 28, 40, 54])

In [46]:
a1 = np.array([2,4,6,8,10])
a1 / 2

array([1., 2., 3., 4., 5.])

In [47]:
a1 // 2

array([1, 2, 3, 4, 5], dtype=int32)

In [49]:
a1 % 3

array([2, 1, 0, 2, 1], dtype=int32)

In [50]:
a1 ** 2

array([  4,  16,  36,  64, 100], dtype=int32)

In [51]:
a2 = np.array([2,3,4,5,6])
a1 ** a2

array([      4,      64,    1296,   32768, 1000000], dtype=int32)

In [52]:
2 / a1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [16]:
# list
l1 = [4,1,4,5,3,6]
l2 = [7,4,2,1,6,7]
l1 < l2

True

In [53]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,7])

In [56]:
a1 < a2

array([ True,  True, False, False,  True,  True])

In [57]:
a1 > a2

array([False, False,  True,  True, False, False])

In [58]:
a1 <= a2

array([ True,  True, False, False,  True,  True])

In [59]:
a1 == a2

array([False, False, False, False, False, False])

## Indexing and Slicing ndarrays

In [17]:
a = np.arange(0,20,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
a[0]

0

In [19]:
a[1]

2

In [20]:
a[6]

12

In [21]:
a[-1]

18

In [22]:
a[-2]

16

In [24]:
a[0:8]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [25]:
a[::]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
a[-8:-3]

array([ 4,  6,  8, 10, 12])

In [27]:
a[::-1]

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

## Reshape and Transpose

In [78]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
a.shape

(16,)

In [80]:
a.ndim

1

In [81]:
a = a.reshape((16,1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [82]:
a.shape

(16, 1)

In [83]:
a = a.reshape((1,16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [84]:
a.shape

(1, 16)

In [85]:
a.ndim

2

In [86]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
a.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [89]:
a = np.arange(36)
a.reshape((1,36))
a.reshape((2,18))
a.reshape((3,12))
a.reshape((4,9))
a.reshape((6,6))
a.reshape((9,4))
a.reshape((12,3))
a.reshape((18,2))
a.reshape((36,1))
print('Total possible 2d shapes : ', 9)

Total possible 2d shapes :  9


In [90]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
a.T# Transpose

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

# ----------------------------------------------------------------------------------

# Functions

In [92]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [93]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [97]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
a = np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [99]:
np.abs([-1,2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [35]:
np.add([1,2,3],[4,5,6],)

array([5, 7, 9])

In [32]:
np.subtract([4,5,6],[1,2,3])

array([3, 3, 3])

In [55]:
np.multiply([1,2,3],[2,3,4])

array([ 2,  6, 12])

In [56]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [57]:
np.maximum(a1,a2)

array([3, 4, 4, 5, 6, 6])

In [58]:
np.minimum(a1,a2)

array([2, 1, 2, 1, 3, 5])

In [59]:
np.greater(a1,a2)

array([False, False,  True,  True, False,  True])

In [60]:
np.less(a1,a2)

array([ True,  True, False, False,  True, False])

In [61]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [62]:
a1.mean()

10.0

In [63]:
np.mean([1,2,3,4,5,6,7,8,9])

5.0

In [64]:
a1.var()

36.666666666666664

In [65]:
a1.std()

6.0553007081949835

In [66]:
np.median(a1)

10.0

In [67]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [69]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [70]:
a.min()

1

In [71]:
a.max()

10

In [72]:
a.sum()

55

In [73]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [74]:
a.shape

(8, 8)

In [75]:
a.mean()

31.5

In [76]:
a.mean(axis = 0)

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [77]:
a.mean(axis = 1)

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [78]:
a.std()

18.472953201911167

In [79]:
a.std(axis = 0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [80]:
a.std(axis = 1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [81]:
a.max()

63

In [82]:
a.max(axis = 0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [83]:
a.max(axis = 1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [84]:
x = np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [85]:
np.argmax(x)

2

In [86]:
np.argmin(x)

0

In [87]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [88]:
np.argmax(a1)

20

In [89]:
np.argmax(a1, axis = 0)

20

In [90]:
np.argmax(a1, axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [91]:
np.argmin(a1, axis = 0)

0

In [92]:
np.argmin(a1, axis = 0)

0

In [93]:
s=a1.ravel()
print(s.shape)
s

(21,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [94]:
a2 = a1.reshape(1,4,4)
a2

ValueError: cannot reshape array of size 21 into shape (1,4,4)

In [95]:
a2.shape

(6,)

In [96]:
a2 = a2.squeeze()
a2

array([3, 4, 2, 1, 6, 5])

In [97]:
a2.shape

(6,)

In [98]:
a2=a2.squeeze()
a2

array([3, 4, 2, 1, 6, 5])

In [ ]:
a2.shape

### Determinant and Inverse

In [99]:
from numpy.linalg import det, inv, eig
a = np.array([4,3,7,9,2,3,9,6,1,4,7,6,11,4,8,7]).reshape((4,4))
a

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7]])

In [100]:
det(a)

527.0000000000001

In [101]:
inv(a)

array([[-0.0170778 , -0.02087287, -0.07969639,  0.10815939],
       [-0.22580645, -0.38709677,  0.61290323,  0.09677419],
       [-0.10436433,  0.31688805, -0.15370019, -0.0056926 ],
       [ 0.27514231, -0.10815939, -0.04933586, -0.07590133]])

In [102]:
eig(a)

(array([22.97864964,  3.76499269, -4.34011564, -1.40352668]),
 array([[-0.51289911, -0.39468612,  0.5270535 ,  0.05108621],
        [-0.41676444,  0.52758299,  0.07812217, -0.85784205],
        [-0.37954612,  0.5045306 ,  0.33673147,  0.494701  ],
        [-0.64744625, -0.55796767, -0.77635266, -0.12949184]]))

### Concatenation

In [103]:
a1 = np.arange(5)
a2 = np.arange(5,10)

In [104]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a1 = a1.reshape(1,5)
a2 = a2.reshape(1,5)
print(a1)
print(a2)

[[0 1 2 3 4]]
[[5 6 7 8 9]]


In [106]:
np.concatenate((a1,a2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [107]:
np.concatenate((a1,a2), axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
np.concatenate((a1,a2), axis = 1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [109]:
a1 = a
a2 = a.T
print(a1)
print()
print(a2)

[[ 4  3  7  9]
 [ 2  3  9  6]
 [ 1  4  7  6]
 [11  4  8  7]]

[[ 4  2  1 11]
 [ 3  3  4  4]
 [ 7  9  7  8]
 [ 9  6  6  7]]


In [110]:
np.concatenate((a1,a2), axis = 0)

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7],
       [ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [111]:
np.concatenate((a1,a2), axis = 1)

array([[ 4,  3,  7,  9,  4,  2,  1, 11],
       [ 2,  3,  9,  6,  3,  3,  4,  4],
       [ 1,  4,  7,  6,  7,  9,  7,  8],
       [11,  4,  8,  7,  9,  6,  6,  7]])

# Random numbers

In [112]:
np.random.randint(1,10)

9

In [113]:
np.random.randint(50)

24

In [114]:
np.random.randint(1,100,10)

array([88, 91, 87, 54, 71, 55, 31,  4, 89, 45])

In [115]:
np.random.randint(1,100,(10,10))

array([[58, 81, 73, 62,  9, 89, 83, 70, 58, 43],
       [11, 15, 51, 32,  1, 95, 37, 25, 81, 85],
       [59, 96, 87,  7, 44, 56, 64, 54, 16, 81],
       [49, 75, 61,  1, 65, 59, 36, 87, 45, 66],
       [98, 53, 55, 19, 24, 66, 15, 82, 75, 67],
       [ 1, 13, 20, 61, 59, 56, 79, 33, 50, 47],
       [99, 94, 23, 88, 13, 37, 72, 95,  6, 98],
       [83, 90, 93, 46, 64, 20,  6, 77, 31, 57],
       [43, 83,  6, 85, 44, 51, 72, 64, 87, 92],
       [97, 27, 85, 47, 40, 67, 39, 68,  2, 93]])

In [116]:
np.random.rand(10)

array([0.32936924, 0.08804286, 0.57046988, 0.31602153, 0.1603803 ,
       0.66591545, 0.31020056, 0.05425633, 0.99246625, 0.70466953])

In [117]:
np.random.randn(10)

array([-0.39845705,  0.70499706,  0.82625228, -1.16206481,  0.68729879,
       -0.09991099,  0.14839055, -1.83805439,  0.2552794 ,  0.24370545])

In [118]:
np.random.randn(3,4)

array([[-0.71820045,  1.69918156, -1.30579623, -0.35965551],
       [ 0.22132388,  0.57059888, -0.6746009 ,  0.13207644],
       [-0.08916301,  0.85083283,  1.55791445,  0.07735546]])

# Conditional Indexing

In [119]:
a = np.random.randint(1,100,(8,8))
a

array([[86, 73, 93, 20, 90, 61,  9, 97],
       [63, 41, 51, 19, 64, 92, 74, 72],
       [76, 10, 64, 39, 42, 40, 12, 90],
       [93, 63, 16, 41, 28, 48, 55, 26],
       [70, 69, 96, 58, 27,  3, 46, 73],
       [52, 40, 32, 99, 35, 69, 17, 13],
       [45, 69, 25, 92, 89, 68, 34, 46],
       [96, 27, 91, 43, 56, 36, 75, 55]])

In [120]:
a[a > 50]

array([86, 73, 93, 90, 61, 97, 63, 51, 64, 92, 74, 72, 76, 64, 90, 93, 63,
       55, 70, 69, 96, 58, 73, 52, 99, 69, 69, 92, 89, 68, 96, 91, 56, 75,
       55])

In [121]:
a[a < 50]

array([20,  9, 41, 19, 10, 39, 42, 40, 12, 16, 41, 28, 48, 26, 27,  3, 46,
       40, 32, 35, 17, 13, 45, 25, 34, 46, 27, 43, 36])

In [122]:
a[a <= 40]

array([20,  9, 19, 10, 39, 40, 12, 16, 28, 26, 27,  3, 40, 32, 35, 17, 13,
       25, 34, 27, 36])

In [123]:
a[a == 40]

array([40, 40])

In [124]:
a[a < 40][a[a < 40] > 20]

array([39, 28, 26, 27, 32, 35, 25, 34, 27, 36])

In [126]:
b = a[a < 40]
b[b > 20]

array([30, 30, 22, 35, 21, 21, 33, 29, 34, 25, 34, 26, 31, 38, 26, 27, 27,
       38, 36, 30, 30, 33, 25])

# Slicing in Multidimensional Arrays

In [125]:
a = np.random.randint(10,100,(10,10))
a

array([[13, 30, 81, 54, 55, 30, 79, 89, 66, 90],
       [55, 51, 56, 99, 43, 11, 71, 50, 64, 60],
       [57, 73, 83, 22, 69, 35, 14, 61, 45, 89],
       [71, 99, 40, 17, 21, 80, 21, 33, 69, 29],
       [79, 34, 78, 53, 81, 69, 25, 45, 18, 49],
       [34, 85, 41, 63, 26, 31, 49, 98, 91, 45],
       [38, 26, 40, 81, 63, 11, 14, 15, 64, 44],
       [76, 50, 27, 27, 18, 73, 38, 50, 58, 36],
       [75, 19, 80, 86, 51, 30, 64, 71, 61, 65],
       [68, 30, 78, 77, 77, 68, 33, 12, 95, 25]])

In [127]:
a.ndim

2

In [128]:
a.shape

(10, 10)

In [129]:
a[4][3]

53

In [130]:

a[:5]

array([[13, 30, 81, 54, 55, 30, 79, 89, 66, 90],
       [55, 51, 56, 99, 43, 11, 71, 50, 64, 60],
       [57, 73, 83, 22, 69, 35, 14, 61, 45, 89],
       [71, 99, 40, 17, 21, 80, 21, 33, 69, 29],
       [79, 34, 78, 53, 81, 69, 25, 45, 18, 49]])

In [131]:
a[:5, :5]

array([[13, 30, 81, 54, 55],
       [55, 51, 56, 99, 43],
       [57, 73, 83, 22, 69],
       [71, 99, 40, 17, 21],
       [79, 34, 78, 53, 81]])

In [132]:
a[:7, :7]

array([[13, 30, 81, 54, 55, 30, 79],
       [55, 51, 56, 99, 43, 11, 71],
       [57, 73, 83, 22, 69, 35, 14],
       [71, 99, 40, 17, 21, 80, 21],
       [79, 34, 78, 53, 81, 69, 25],
       [34, 85, 41, 63, 26, 31, 49],
       [38, 26, 40, 81, 63, 11, 14]])

In [133]:
a[:9,4:]

array([[55, 30, 79, 89, 66, 90],
       [43, 11, 71, 50, 64, 60],
       [69, 35, 14, 61, 45, 89],
       [21, 80, 21, 33, 69, 29],
       [81, 69, 25, 45, 18, 49],
       [26, 31, 49, 98, 91, 45],
       [63, 11, 14, 15, 64, 44],
       [18, 73, 38, 50, 58, 36],
       [51, 30, 64, 71, 61, 65]])

In [134]:
a[2:8,2:8:2]

array([[83, 69, 14],
       [40, 21, 21],
       [78, 81, 25],
       [41, 26, 49],
       [40, 63, 14],
       [27, 18, 38]])

In [135]:
b = a[1:8, 2:8]
b

array([[56, 99, 43, 11, 71, 50],
       [83, 22, 69, 35, 14, 61],
       [40, 17, 21, 80, 21, 33],
       [78, 53, 81, 69, 25, 45],
       [41, 63, 26, 31, 49, 98],
       [40, 81, 63, 11, 14, 15],
       [27, 27, 18, 73, 38, 50]])

In [136]:
b[b > 40]

array([56, 99, 43, 71, 50, 83, 69, 61, 80, 78, 53, 81, 69, 45, 41, 63, 49,
       98, 81, 63, 73, 50])

In [137]:
a[1:8, 2:8][a[1:8, 2:8] > 40]

array([56, 99, 43, 71, 50, 83, 69, 61, 80, 78, 53, 81, 69, 45, 41, 63, 49,
       98, 81, 63, 73, 50])